const MAKE_MOVE = 'MAKE_MOVE';
const PLAY_AGAIN = 'PLAY_AGAIN';
const JUMP_TO = 'JUMP_TO';
const BACK_STEP = 'BACK_STEP';
const NEXT_STEP = 'NEXT_STEP';

exports.MAKE_MOVE = MAKE_MOVE;
exports.PLAY_AGAIN = PLAY_AGAIN;
exports.JUMP_TO = JUMP_TO;
exports.BACK_STEP = BACK_STEP;
exports.NEXT_STEP = NEXT_STEP;



